#!/usr/bin/env bash
cd $(dirname $0)

GHOSTNAME="ghost"

if [ ! -z "$1" ]
  then
    GHOSTNAME="$1"
fi

echo "Creating ghost in teams/$GHOSTNAME"
cp -r team017 "$GHOSTNAME"
find "$GHOSTNAME" -name "*.java" | xargs sed -i "s/team017/$GHOSTNAME/g"
