#!/usr/bin/env bash
# Usage:
#  ./analyze        # create latest.log
#  ./analyze better # create better.log

LOGFILE=locallogs/latest.log

if [ ! -z "$1" ]
  then
    LOGFILE=locallogs/$1.log
fi

ant analyze | tee $LOGFILE
echo "Match log saved to $LOGFILE"
